### ISSUE TITLE
CSS splitting per component

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/design-systems#11]
Since `CookieConsent` will be used in the PunchUp project, splitting CSS for each component will allow the developer to import only necessary stylesheets.

**Current usage**

```js
import '@wevisdemo/ui/styles/index.css';
```

**Expectation**

```js
/* Required typography utility classes */
import '@wevisdemo/ui/styles/typography.css';

/* Used components */
import '@wevisdemo/ui/styles/cookie-consent.css';
import '@wevisdemo/ui/styles/button.css';
```

Note that the `index.css` should be kept the same.

**Comment by rootEnginear** [comment]
Fixed in 8d8a33aa39cbe34ee650ec65084651a036899033 and b96be6f1f5e8144a41125ab18c3058d053bc33ef
