### ISSUE TITLE
WvNavButton overflows on mobile when WvNavbar always show slot

### ISSUE THREAD

**Issue by rootEnginear** [wevisdemo/design-systems#2]
When `alwayShowSlot` is `true` on `<WvNavbar>`, `<WvNavButton>` will overflow on mobile viewport.

![image](https://user-images.githubusercontent.com/7108662/201745896-2e6f0c41-43b8-4457-a75f-a43ac6bd783b.png)

## Details
- UI Version: 5.0.0
- Framework: SvelteKit

**Comment by Th1nkK1D** [comment]
Should be fixed in [5.1.0](https://github.com/wevisdemo/design-systems/releases/tag/v5.1.0)
